export GPG_TTY=$(tty)
export NOTE_DIR=$HOME/storage/shared/projects/notes
export DOTFILE_DIR=$HOME/storage/shared/projects/dotfiles

alias ls="ls --group-directories-first -A -s -h -1"
alias cdn="cd $NOTE_DIR"
alias cdd="cd $DOTFILE_DIR"
alias g="git"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit"                                
alias gp="git push"
alias gpl="git pull"
alias gco="git checkout"
alias gs="git status"
alias gl="git log"
alias gm="git merge"
alias gw="git worktree"
alias gst="git stash"
alias gstc="git stash clear"                         
alias gstp="git stash pop"
