export GPG_TTY=$(tty)
alias ls="ls --group-directories-first -A -s -h -1"
alias cdn="cd ~/storage/shared/projects/notes"
alias cdno="cd ~/storage/shared/projects/obsidian-notes"
alias g="git"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit"                                alias gp="git push"
alias gpl="git pull"
alias gco="git checkout"
alias gs="git status"
alias gl="git log"
alias gm="git merge"
alias gw="git worktree"
alias gst="git stash"
alias gstc="git stash clear"                         alias gstp="git stash clear"
