#!/bin/bash

ls todos | awk -F '.' '{ print $1 }' | xargs -I {} bash -c "scribe {}" \
    | xargs -I {} echo {} | sed 's/^[[:space:]]*//g' | sed 's/[[:space:]]*$//g' | xargs -0 \
        -I {} git commit -m {} 
