#!/bin/sh

color=$(cat $HOME/.cache/wal/colors.json| jq ".colors.color1" -r)
pattern="s/icon-color/$color/g"

sed -e $pattern $HOME/projects/dotfiles/waybar/config-template > $HOME/.config/waybar/config
