#!/bin/sh

curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.3-stable.tar.xz > $HOME/downloads/flutter_linux 
tar xf $HOME/downloads/flutter_linux $HOME/flutter

flutter precache

# disable bullshit
flutter config --no-analytics
flutter --disable-telemetry

flutter config --android-sdk /usr/bin/android-studio

ls /usr/bin/android-studio || yay -S android-studio
