#!/bin/sh

echo "enter common password for keys"
read -s password

files=$(ls $HOME/.ssh | grep _ed25519 | grep -v .pub)
for file in $files 
do
    SSH_PASS=$password DISPLAY=1 SSH_ASKPASS=$HOME/projects/dotfiles/custom/ssh-pass-pass ssh-add $HOME/.ssh/$file < /dev/null
done
