#!/bin/sh

if [[ $XDG_SESSION_TYPE -eq "wayland" ]]; then
    swaybg -i ~/projects/dotfiles/images/background.* && \
    wal -n -i ~/projects/dotfiles/images/background.*
else
    nitrogen --restore && wal -n -i ~/projects/dotfiles/images/background.* && sh ~/projects/dotfiles/custom/start-polybar.sh 
fi
