vim.cmd('ab ./c ✓')
vim.cmd('ab ./x ✗ ')
vim.cmd('ab ./w ⚠️')
vim.cmd('ab ./u 🕑')
vim.cmd('ab ./m 🪄')
vim.cmd('ab ./h ♥')
vim.cmd('ab ./s ☠')
vim.cmd('ab ./f ⚑')
vim.cmd('ab ./a ➜ ')
vim.cmd('ab ./g ⬡  ')
