set exrc
set number
set relativenumber
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nohlsearch
set hidden
set noerrorbells
set nowrap
set noswapfile
set undofile
set undodir=~/.vim/undodir
set incsearch
set scrolloff=15
set signcolumn=yes
set colorcolumn=90
set encoding=UTF-8
set noshowmode
set updatetime=50
set spell spelllang=en_gb
set clipboard+=unnamedplus
