vim.opt.exrc = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.hidden = true
vim.opt.undofile = true
vim.opt.undodir = '/home/jackboxx/.vim/undodir'
vim.opt.incsearch  =  true
vim.opt.scrolloff = 15
vim.opt.signcolumn = 'yes'
vim.opt.colorcolumn = '90'
vim.opt.textwidth = 90
vim.opt.encoding  =  'UTF-8'
vim.opt.updatetime=50
vim.opt.spell = true
vim.opt.spelllang = 'en_us'
vim.opt.hlsearch = false
vim.opt.errorbells = false
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.showmode = false
vim.cmd('set clipboard+=unnamedplus')
